spring.application.name=Task-Management-Backend
jwt.secret=Z3ZqM2J2cXlXQk9KcFJ2Q3J5bGZ2a3N6Q2h0T0xvV0x5N1Z0Zg==
jwt.expiration=86400000
spring.datasource.url=jdbc:postgresql://localhost:5432/TASKDB
spring.datasource.username=adamusulaimanmuhammad
spring.datasource.password=Islam2005
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update